name: prod-build-and-deploy

run-name: Prod - build and deploy

on:
  push:
    tags:
      - v*

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      - run: npm run lint
      - run: npm run format

  build-and-push:
    needs: check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        run: |
          docker build -f Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/sc-bar-react-next:${GITHUB_REF#refs/tags/} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/sc-bar-react-next:${GITHUB_REF#refs/tags/}
        env:
          DOCKER_CLI_ASK_CONFIRM: 'false'
